export const DESTINATIONS = [
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'europe',
    badge: '🏛️ History & Culture',
    badgeColor: '#7C3AED',
    rating: 4.9,
    reviews: 2841,
    vibes: ['history', 'foodie', 'art'],
    budget: ['standard', 'premium'],
    tagline: 'Where every cobblestone tells a story',
    duration: '4–6 days',
    prompt: '5 days in Rome: ancient ruins, Vatican, hidden trattorias & sunset over the Tiber',
    gradient: 'from-amber-900/70 via-orange-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
    emoji: '🍕',
    bgColor: '#C8956C',
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'asia',
    badge: '🌸 Temples & Zen',
    badgeColor: '#DB2777',
    rating: 4.8,
    reviews: 3102,
    vibes: ['history', 'nature', 'foodie'],
    budget: ['standard', 'premium'],
    tagline: 'Ancient Japan, perfectly preserved',
    duration: '5–7 days',
    prompt: '5 days in Kyoto: temples, bamboo groves, tea ceremonies & kaiseki dining',
    gradient: 'from-pink-900/70 via-rose-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&auto=format&fit=crop&q=80',
    emoji: '🌸',
    bgColor: '#C8929A',
  },
  {
    id: 'swiss-alps',
    name: 'Swiss Alps',
    country: 'Switzerland',
    region: 'europe',
    badge: '⛰️ Adventure & Nature',
    badgeColor: '#0891B2',
    rating: 4.9,
    reviews: 1876,
    vibes: ['nature', 'art'],
    budget: ['premium'],
    tagline: 'Breathtaking peaks, crystal lakes',
    duration: '6–8 days',
    prompt: '7 days in Swiss Alps: Zermatt, Interlaken, scenic train rides & alpine hikes',
    gradient: 'from-sky-900/70 via-blue-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&auto=format&fit=crop&q=80',
    emoji: '🏔️',
    bgColor: '#6B93B0',
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'africa',
    badge: '🕌 Souks & Spice',
    badgeColor: '#D97706',
    rating: 4.7,
    reviews: 1654,
    vibes: ['shopping', 'history', 'foodie'],
    budget: ['economy', 'standard'],
    tagline: 'A sensory explosion in every alley',
    duration: '3–5 days',
    prompt: '4 days in Marrakech: medina souks, riad stays, Djemaa el-Fna & Sahara day trip',
    gradient: 'from-orange-900/70 via-amber-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&auto=format&fit=crop&q=80',
    emoji: '🕌',
    bgColor: '#C8895A',
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'USA',
    region: 'americas',
    badge: '🗽 City & Nightlife',
    badgeColor: '#1D4ED8',
    rating: 4.8,
    reviews: 4201,
    vibes: ['nightlife', 'art', 'foodie', 'shopping'],
    budget: ['standard', 'premium'],
    tagline: 'The city that never stops surprising',
    duration: '5–7 days',
    prompt: '6 days in New York: Brooklyn food scene, MoMA, Manhattan skyline, jazz bars & Times Square',
    gradient: 'from-slate-900/70 via-gray-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&auto=format&fit=crop&q=80',
    emoji: '🗽',
    bgColor: '#6B7BA0',
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'asia',
    badge: '🌴 Spiritual & Tropical',
    badgeColor: '#059669',
    rating: 4.7,
    reviews: 3487,
    vibes: ['nature', 'foodie', 'art'],
    budget: ['economy', 'standard'],
    tagline: 'Jungle temples and infinite sunsets',
    duration: '7–10 days',
    prompt: '8 days in Bali: Ubud rice terraces, Uluwatu temples, surf lessons & organic cuisine',
    gradient: 'from-green-900/70 via-emerald-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
    emoji: '🌴',
    bgColor: '#6B9B7A',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'europe',
    badge: '🎨 Art & Architecture',
    badgeColor: '#DC2626',
    rating: 4.8,
    reviews: 2934,
    vibes: ['art', 'foodie', 'nightlife'],
    budget: ['standard', 'premium'],
    tagline: 'Gaudí, tapas, and Mediterranean magic',
    duration: '4–6 days',
    prompt: '5 days in Barcelona: Sagrada Família, Gothic Quarter, pintxos crawl & beach at Barceloneta',
    gradient: 'from-red-900/70 via-rose-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&auto=format&fit=crop&q=80',
    emoji: '🎨',
    bgColor: '#C8726B',
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'oceania',
    badge: '🪂 Adventure Capital',
    badgeColor: '#7C3AED',
    rating: 4.9,
    reviews: 1203,
    vibes: ['nature', 'nightlife'],
    budget: ['premium'],
    tagline: 'Bungee jumps and fjord-blue lakes',
    duration: '4–6 days',
    prompt: '5 days in Queenstown: bungee jumping, Milford Sound, Fergburger & Remarkables ski field',
    gradient: 'from-violet-900/70 via-purple-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1607427293702-036933bbf746?w=800&auto=format&fit=crop&q=80',
    emoji: '🪂',
    bgColor: '#7B7AB0',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'europe',
    badge: '🥐 Romance & Art',
    badgeColor: '#E11D48',
    rating: 4.8,
    reviews: 5410,
    vibes: ['art', 'foodie', 'history'],
    budget: ['premium'],
    tagline: 'Café culture and iconic landmarks',
    duration: '4–6 days',
    prompt: '5 days in Paris: Louvre, Eiffel Tower, Montmartre cafés & Seine cruise',
    gradient: 'from-rose-900/70 via-pink-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
    emoji: '🥐',
    bgColor: '#B78C91',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'asia',
    badge: '🗼 Neon & Tradition',
    badgeColor: '#EA580C',
    rating: 4.9,
    reviews: 6203,
    vibes: ['nightlife', 'foodie', 'shopping'],
    budget: ['standard', 'premium'],
    tagline: 'A dizzying blend of future and past',
    duration: '5–8 days',
    prompt: '7 days in Tokyo: Shibuya crossing, sushi masterclasses, Akihabara & ancient shrines',
    gradient: 'from-orange-900/70 via-amber-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80',
    emoji: '🗼',
    bgColor: '#967C6B',
  },
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    region: 'europe',
    badge: '🎡 Royal & Historic',
    badgeColor: '#2563EB',
    rating: 4.7,
    reviews: 4892,
    vibes: ['history', 'art', 'shopping'],
    budget: ['standard', 'premium'],
    tagline: 'Pubs, palaces, and world-class museums',
    duration: '5–7 days',
    prompt: '6 days in London: British Museum, West End shows, Borough Market & royal parks',
    gradient: 'from-blue-900/70 via-indigo-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
    emoji: '🎡',
    bgColor: '#7583A8',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'oceania',
    badge: '🏄 Beaches & Harbors',
    badgeColor: '#0EA5E9',
    rating: 4.8,
    reviews: 2130,
    vibes: ['nature', 'foodie', 'nightlife'],
    budget: ['premium'],
    tagline: 'Sun-drenched coasts and harbor sails',
    duration: '6–10 days',
    prompt: '8 days in Sydney: Opera House, Bondi surfing, coastal walks & harbor dining',
    gradient: 'from-cyan-900/70 via-sky-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&auto=format&fit=crop&q=80',
    emoji: '🏄',
    bgColor: '#6FA4B5',
  },
  {
    id: 'rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'americas',
    badge: '🏖️ Sun & Samba',
    badgeColor: '#16A34A',
    rating: 4.6,
    reviews: 1845,
    vibes: ['nature', 'nightlife', 'art'],
    budget: ['economy', 'standard'],
    tagline: 'Golden beaches beneath tropical mountains',
    duration: '5–7 days',
    prompt: '6 days in Rio: Copacabana, Christ the Redeemer, samba clubs & Tijuca forest',
    gradient: 'from-emerald-900/70 via-green-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&auto=format&fit=crop&q=80',
    emoji: '🏖️',
    bgColor: '#6FA378',
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'africa',
    badge: '🐧 Wildlife & Wine',
    badgeColor: '#8B5CF6',
    rating: 4.9,
    reviews: 2314,
    vibes: ['nature', 'foodie', 'history'],
    budget: ['economy', 'standard'],
    tagline: 'Rugged coastlines and vineyards',
    duration: '6–9 days',
    prompt: '7 days in Cape Town: Table Mountain, penguin beaches, wine tasting & Robben Island',
    gradient: 'from-purple-900/70 via-violet-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&auto=format&fit=crop&q=80',
    emoji: '🐧',
    bgColor: '#877EA3',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'asia',
    badge: '✨ Luxury & Desert',
    badgeColor: '#EAB308',
    rating: 4.7,
    reviews: 3845,
    vibes: ['shopping', 'nightlife', 'art'],
    budget: ['premium'],
    tagline: 'Futuristic skylines and golden dunes',
    duration: '4–6 days',
    prompt: '5 days in Dubai: Burj Khalifa, desert safaris, mega-malls & luxury beach clubs',
    gradient: 'from-yellow-900/70 via-amber-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
    emoji: '✨',
    bgColor: '#B5A574',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    region: 'europe',
    badge: '☕ Spices & Bazaars',
    badgeColor: '#B91C1C',
    rating: 4.8,
    reviews: 2987,
    vibes: ['history', 'shopping', 'foodie'],
    budget: ['economy', 'standard'],
    tagline: 'Where continents collide in stunning beauty',
    duration: '4–7 days',
    prompt: '6 days in Istanbul: Hagia Sophia, Grand Bazaar, Bosphorus cruise & Turkish baths',
    gradient: 'from-red-900/70 via-rose-800/50 to-transparent',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&auto=format&fit=crop&q=80',
    emoji: '☕',
    bgColor: '#A37272',
  },
];

const TELEMETRY_MAP = {
  rome: {
    weather: '☀️ 24°C • Perfect Spring Pacing',
    aiTip: '💡 AI Verdict: Best visited for 5 days to balance historic landmarks with relaxation.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 41.9028, lng: 12.4964 }
  },
  kyoto: {
    weather: '🌸 18°C • Cherry Blossom Peak',
    aiTip: '💡 AI Verdict: #1 Top Rated Cultural Retreat in Asia right now.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: 35.0116, lng: 135.7681 }
  },
  'swiss-alps': {
    weather: '🌤️ 14°C • Crisp Alpine Air',
    aiTip: '💡 AI Verdict: Scenic train loops & light valley hikes are prime right now.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: 46.5580, lng: 8.5610 }
  },
  marrakech: {
    weather: '☀️ 28°C • Warm & Sunny',
    aiTip: '💡 AI Verdict: 4 days is the sweet spot for souks, riads, and a desert excursion.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 31.6295, lng: -8.0088 }
  },
  'new-york': {
    weather: '☀️ 22°C • Clear Rooftop Season',
    aiTip: '💡 AI Verdict: Ideal for urban nightlife & architectural discovery.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 40.7128, lng: -74.0060 }
  },
  bali: {
    weather: '🌴 29°C • Tropical Breeze',
    aiTip: '💡 AI Verdict: Split time between Ubud rice terraces and Uluwatu coast.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: -8.4095, lng: 115.1889 }
  },
  barcelona: {
    weather: '☀️ 25°C • Mediterranean Warmth',
    aiTip: '💡 AI Verdict: Reserve Sagrada Família early; evening tapas crawls recommended.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 41.3851, lng: 2.1734 }
  },
  queenstown: {
    weather: '⛰️ 12°C • Crisp Mountain Views',
    aiTip: '💡 AI Verdict: Top choice for thrill seekers; 5 days covers Milford Sound & skiing.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: -45.0312, lng: 168.6626 }
  },
  paris: {
    weather: '🥐 20°C • Mild & Romantic',
    aiTip: '💡 AI Verdict: Evening Seine cruise combined with Montmartre sunset is unbeatable.',
    crowdLevel: '🔴 High Season',
    coords: { lat: 48.8566, lng: 2.3522 }
  },
  tokyo: {
    weather: '🗼 21°C • Ideal City Walking',
    aiTip: '💡 AI Verdict: Group neighborhoods by transit line (Shibuya/Shinjuku then Asakusa/Akihabara).',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 35.6762, lng: 139.6503 }
  },
  london: {
    weather: '🌤️ 17°C • Classic English Sunshine',
    aiTip: '💡 AI Verdict: Free national museums make this exceptional value right now.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: 51.5074, lng: -0.1278 }
  },
  sydney: {
    weather: '🏄 24°C • Coastal Sunshine',
    aiTip: '💡 AI Verdict: The Bondi to Coogee coastal walk is in peak window.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: -33.8688, lng: 151.2093 }
  },
  rio: {
    weather: '🏖️ 27°C • Golden Beach Days',
    aiTip: '💡 AI Verdict: Sunset at Sugarloaf Mountain followed by Lapa samba nightlife.',
    crowdLevel: '🟡 Moderate Season',
    coords: { lat: -22.9068, lng: -43.1729 }
  },
  'cape-town': {
    weather: '🐧 23°C • Clear Table Mountain Views',
    aiTip: '💡 AI Verdict: Combine wine country tasting with Boulders Beach penguin colony.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: -33.9249, lng: 18.4241 }
  },
  dubai: {
    weather: '✨ 32°C • Evening Desert Breezes',
    aiTip: '💡 AI Verdict: Late afternoon sunset dune safaris and rooftop lounges are prime.',
    crowdLevel: '🔴 High Season',
    coords: { lat: 25.2048, lng: 55.2708 }
  },
  istanbul: {
    weather: '☕ 22°C • Bosphorus Breeze',
    aiTip: '💡 AI Verdict: Cross continents by ferry at sunset; explore hidden rooftop tea gardens.',
    crowdLevel: '🟢 Low Crowds',
    coords: { lat: 41.0082, lng: 28.9784 }
  }
};

DESTINATIONS.forEach(d => {
  if (TELEMETRY_MAP[d.id]) {
    Object.assign(d, TELEMETRY_MAP[d.id]);
  }
});
